In [2]:
import pandas as pd
import concurrent.futures


chunksize = 10000
json_reader = pd.read_json('yelp_academic_dataset_review.json', lines=True, chunksize=chunksize)

df_list = []
for chunk in json_reader:
    df_list.append(chunk)
    
# Now df_list is a list of dataframes, which you can concatenate to get a single dataframe
reviewDF = pd.concat(df_list)

display(reviewDF)

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3,0,0,0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5,1,0,1,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18
2,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3,0,0,0,Family diner. Had the buffet. Eclectic assortm...,2014-02-05 20:30:30
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5,1,0,1,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03
4,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4,1,0,1,Cute interior and owner (?) gave us tour of up...,2017-01-14 20:54:15
...,...,...,...,...,...,...,...,...,...
6990275,H0RIamZu0B0Ei0P4aeh3sQ,qskILQ3k0I_qcCMI-k6_QQ,jals67o91gcrD4DC81Vk6w,5,1,2,1,Latest addition to services from ICCU is Apple...,2014-12-17 21:45:20
6990276,shTPgbgdwTHSuU67mGCmZQ,Zo0th2m8Ez4gLSbHftiQvg,2vLksaMmSEcGbjI5gywpZA,5,2,1,2,"This spot offers a great, affordable east week...",2021-03-31 16:55:10
6990277,YNfNhgZlaaCO5Q_YJR4rEw,mm6E4FbCMwJmb7kPDZ5v2Q,R1khUUxidqfaJmcpmGd4aw,4,1,0,0,This Home Depot won me over when I needed to g...,2019-12-30 03:56:30
6990278,i-I4ZOhoX70Nw5H0FwrQUA,YwAMC-jvZ1fvEUum6QkEkw,Rr9kKArrMhSLVE9a53q-aA,5,1,0,0,For when I'm feeling like ignoring my calorie-...,2022-01-19 18:59:27
6990279,RwcKOdEuLRHNJe4M9-qpqg,6JehEvdoCvZPJ_XIxnzIIw,VAeEXLbEcI9Emt9KGYq9aA,3,10,3,7,Located in the 'Walking District' in Nashville...,2018-01-02 22:50:47

In [4]:
chunksize = 10000
json_reader = pd.read_json('yelp_academic_dataset_business.json', lines=True, chunksize=chunksize)

df_listBusiness = []
for chunk in json_reader:
    df_listBusiness.append(chunk)
    
# Now df_list is a list of dataframes, which you can concatenate to get a single dataframe
businessDF = pd.concat(df_listBusiness)

display(businessDF)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,7,0,{'ByAppointmentOnly': 'True'},"Doctors, Traditional Chinese Medicine, Naturop...",None
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,15,1,{'BusinessAcceptsCreditCards': 'True'},"Shipping Centers, Local Services, Notaries, Ma...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-18:30', ..."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,22,0,"{'BikeParking': 'True', 'BusinessAcceptsCredit...","Department Stores, Shopping, Fashion, Home & G...","{'Monday': '8:0-22:0', 'Tuesday': '8:0-22:0', ..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,40.338183,-75.471659,4.5,13,1,"{'BusinessAcceptsCreditCards': 'True', 'Wheelc...","Brewpubs, Breweries, Food","{'Wednesday': '14:0-22:0', 'Thursday': '16:0-2..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150341,IUQopTMmYQG-qRtBk-8QnA,Binh's Nails,3388 Gateway Blvd,Edmonton,AB,T6J 5H2,53.468419,-113.492054,3.0,13,1,"{'ByAppointmentOnly': 'False', 'RestaurantsPri...","Nail Salons, Beauty & Spas","{'Monday': '10:0-19:30', 'Tuesday': '10:0-19:3..."
150342,c8GjPIOTGVmIemT7j5_SyQ,Wild Birds Unlimited,2813 Bransford Ave,Nashville,TN,37204,36.115118,-86.766925,4.0,5,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Pets, Nurseries & Gardening, Pet Stores, Hobby...","{'Monday': '9:30-17:30', 'Tuesday': '9:30-17:3..."
150343,_QAMST-NrQobXduilWEqSw,Claire's Boutique,"6020 E 82nd St, Ste 46",Indianapolis,IN,46250,39.908707,-86.065088,3.5,8,1,"{'RestaurantsPriceRange2': '1', 'BusinessAccep...","Shopping, Jewelry, Piercing, Toy Stores, Beaut...",None
150344,mtGm22y5c2UHNXDFAjaPNw,Cyclery & Fitness Center,2472 Troy Rd,Edwardsville,IL,62025,38.782351,-89.950558,4.0,24,1,"{'BusinessParking': '{'garage': False, 'street...","Fitness/Exercise Equipment, Eyewear & Optician...","{'Monday': '9:0-20:0', 'Tuesday': '9:0-20:0', ..."
150345,jV_XOycEzSlTx-65W906pg,Sic Ink,238 Apollo Beach Blvd,Apollo beach,FL,33572,27.771002,-82.394910,4.5,9,1,"{'WheelchairAccessible': 'True', 'BusinessAcce...","Beauty & Spas, Permanent Makeup, Piercing, Tattoo","{'Tuesday': '12:0-19:0', 'Wednesday': '12:0-19..."

In [5]:
merged_df = pd.merge(reviewDF, businessDF, on='business_id', how='outer')

In [6]:
display(merged_df)

,review_id,user_id,business_id,stars_x,useful,funny,cool,text,date,name,...,state,postal_code,latitude,longitude,stars_y,review_count,is_open,attributes,categories,hours
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3,0,0,0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11,Turning Point of North Wales,...,PA,19454,40.210196,-75.223639,3.0,169,1,"{'NoiseLevel': 'u'average'', 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'..."
1,VJxlBnJmCDIy8DFG0kjSow,Iaee7y6zdSB3B-kRCo4z1w,XQfwVwDr-v0ZS3_CbbE5Xw,2,0,0,0,This is the second time we tried turning point...,2017-05-13 17:06:55,Turning Point of North Wales,...,PA,19454,40.210196,-75.223639,3.0,169,1,"{'NoiseLevel': 'u'average'', 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'..."
2,S6pQZQocMB1WHMjTRbt77A,ejFxLGqQcWNLdNByJlIhnQ,XQfwVwDr-v0ZS3_CbbE5Xw,4,2,0,1,The place is cute and the staff was very frien...,2017-08-08 00:58:18,Turning Point of North Wales,...,PA,19454,40.210196,-75.223639,3.0,169,1,"{'NoiseLevel': 'u'average'', 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'..."
3,WqgTKVqWVHDHjnjEsBvUgg,f7xa0p_1V9lx53iIGN5Sug,XQfwVwDr-v0ZS3_CbbE5Xw,3,0,0,0,We came on a Saturday morning after waiting a ...,2017-11-19 02:20:23,Turning Point of North Wales,...,PA,19454,40.210196,-75.223639,3.0,169,1,"{'NoiseLevel': 'u'average'', 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'..."
4,M0wzFFb7pefOPcxeRVbLag,dCooFVCk8M1nVaQqcfTL3Q,XQfwVwDr-v0ZS3_CbbE5Xw,2,0,0,0,"Mediocre at best. The decor is very nice, and ...",2017-09-09 17:49:47,Turning Point of North Wales,...,PA,19454,40.210196,-75.223639,3.0,169,1,"{'NoiseLevel': 'u'average'', 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6990275,0gai4MzBzFCa7JsS31RRjg,xHu1jmrnv4DdJMuC8IxeRg,vI4vyi1dfG93oAiSRFDymA,1,2,0,0,Ridiculous wait times. I showed up right on ti...,2018-06-05 14:25:32,Aesthetic Dermatology Associates,...,PA,19301,40.045448,-75.501140,2.5,5,1,"{'BikeParking': 'True', 'WheelchairAccessible'...","Medical Spas, Doctors, Laser Hair Removal, Der...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-17:30..."
6990276,7MZu6bFdFoqr7MyPKqvoew,aYveEctPYcZiubXyEgLhTA,vI4vyi1dfG93oAiSRFDymA,5,4,1,2,Love this office. All the staff us super kind ...,2020-02-17 01:53:23,Aesthetic Dermatology Associates,...,PA,19301,40.045448,-75.501140,2.5,5,1,"{'BikeParking': 'True', 'WheelchairAccessible'...","Medical Spas, Doctors, Laser Hair Removal, Der...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-17:30..."
6990277,3emHuLQvuAw0l66TzSWmKA,oz-So7Kwo5tW51HrT-BgIg,vI4vyi1dfG93oAiSRFDymA,1,0,0,0,It was a HUGE mistake to give this place a try...,2021-09-22 16:51:46,Aesthetic Dermatology Associates,...,PA,19301,40.045448,-75.501140,2.5,5,1,"{'BikeParking': 'True', 'WheelchairAccessible'...","Medical Spas, Doctors, Laser Hair Removal, Der...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-17:30..."
6990278,T-adPwD-eP2LvuDINKOA9g,09zj3b4tM-xJjozvtk34wQ,vI4vyi1dfG93oAiSRFDymA,1,0,0,0,Friendly staff but the praise ends there. Gett...,2021-03-09 19:21:44,Aesthetic Dermatology Associates,...,PA,19301,40.045448,-75.501140,2.5,5,1,"{'BikeParking': 'True', 'WheelchairAccessible'...","Medical Spas, Doctors, Laser Hair Removal, Der...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-17:30..."
6990279,lKSY-hIMd9MX8Z5fRpUgDg,hyfUdXDmgqA4GI3S11I69w,vI4vyi1dfG93oAiSRFDymA,5,0,0,0,Had a great experience! Professional and frien...,2018-07-20 16:11:21,Aesthetic Dermatology Associates,...,PA,19301,40.045448,-75.501140,2.5,5,1,"{'BikeParking': 'True', 'WheelchairAccessible'...","Medical Spas, Doctors, Laser Hair Removal, Der...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-17:30..."

In [18]:
filtered_df = merged_df[merged_df['categories'].str.contains('Restaurant', case=False, na=False)]
filtered_df = filtered_df[filtered_df['city'].str.contains('Philadelphia', case=False, na=False)]

display(filtered_df)

,review_id,user_id,business_id,stars_x,useful,funny,cool,text,date,name,...,state,postal_code,latitude,longitude,stars_y,review_count,is_open,attributes,categories,hours
374,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5,1,0,1,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03,Zaika,...,PA,19114,40.079848,-75.025080,4.0,181,1,"{'Caters': 'True', 'Ambience': '{'romantic': F...","Halal, Pakistani, Restaurants, Indian","{'Tuesday': '11:0-21:0', 'Wednesday': '11:0-21..."
375,HME_ksGph3se7Aze5hxa-Q,kSMOJwJXuEUqzfmuFncK4A,kxX2SOes4o-D3ZQBkiMRfA,2,0,0,1,Dine-in gets 2 stars. Disappointing service & ...,2014-07-13 17:25:47,Zaika,...,PA,19114,40.079848,-75.025080,4.0,181,1,"{'Caters': 'True', 'Ambience': '{'romantic': F...","Halal, Pakistani, Restaurants, Indian","{'Tuesday': '11:0-21:0', 'Wednesday': '11:0-21..."
376,EJWyA5wpdVMji1j4TwSZqQ,mqBWACmaHflW4eh_Ofp16Q,kxX2SOes4o-D3ZQBkiMRfA,5,13,6,5,After a long hiatus from reviewing I have awak...,2010-08-20 19:16:04,Zaika,...,PA,19114,40.079848,-75.025080,4.0,181,1,"{'Caters': 'True', 'Ambience': '{'romantic': F...","Halal, Pakistani, Restaurants, Indian","{'Tuesday': '11:0-21:0', 'Wednesday': '11:0-21..."
377,T_kAb2NeylB-JdNDKphryw,Z-xgVb4nM42943m2wbBkFw,kxX2SOes4o-D3ZQBkiMRfA,5,1,1,1,We've eaten here 3 times and it seems that eac...,2017-01-02 14:25:26,Zaika,...,PA,19114,40.079848,-75.025080,4.0,181,1,"{'Caters': 'True', 'Ambience': '{'romantic': F...","Halal, Pakistani, Restaurants, Indian","{'Tuesday': '11:0-21:0', 'Wednesday': '11:0-21..."
378,NENaCqb6TNj5CyY1LOdI6Q,2SEoXb6r6hPKrl9V9VzBgA,kxX2SOes4o-D3ZQBkiMRfA,5,0,0,0,Came to Philly for a family event but stayed a...,2015-07-28 17:15:20,Zaika,...,PA,19114,40.079848,-75.025080,4.0,181,1,"{'Caters': 'True', 'Ambience': '{'romantic': F...","Halal, Pakistani, Restaurants, Indian","{'Tuesday': '11:0-21:0', 'Wednesday': '11:0-21..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6989913,l6mqZx5do_w7dLBEeDWVDg,reFwg-F-MCoRS1pA2YexMg,BEuGzy5gxtGyOEk8iwDfTg,5,1,0,0,Very friendly people making great food at a re...,2020-08-02 00:06:32,Kaku Latin Food,...,PA,19134,39.990395,-75.104252,5.0,5,1,"{'RestaurantsDelivery': 'True', 'RestaurantsTa...","Cajun/Creole, Caribbean, Restaurants, Event Pl...","{'Monday': '8:0-19:0', 'Tuesday': '8:0-19:0', ..."
6989914,eYq5ckB294CqkRFqfR5gNg,dh3UhfqpFSoCitl8WCrdfw,BEuGzy5gxtGyOEk8iwDfTg,5,1,0,0,I've had these pictures to post this review fo...,2021-03-20 07:33:23,Kaku Latin Food,...,PA,19134,39.990395,-75.104252,5.0,5,1,"{'RestaurantsDelivery': 'True', 'RestaurantsTa...","Cajun/Creole, Caribbean, Restaurants, Event Pl...","{'Monday': '8:0-19:0', 'Tuesday': '8:0-19:0', ..."
6989915,RmmdxkfF9f77yLsMKvwTAA,nXwPLYvazD_Nd2Sar3eSWA,BEuGzy5gxtGyOEk8iwDfTg,5,1,1,0,"Chicken stew is amazing, fresh juices are deli...",2020-11-20 06:39:38,Kaku Latin Food,...,PA,19134,39.990395,-75.104252,5.0,5,1,"{'RestaurantsDelivery': 'True', 'RestaurantsTa...","Cajun/Creole, Caribbean, Restaurants, Event Pl...","{'Monday': '8:0-19:0', 'Tuesday': '8:0-19:0', ..."
6989916,S8lVRBNhs1XpTVQlahViYw,MlOJCxiiB1TeZN-is2Q4SA,BEuGzy5gxtGyOEk8iwDfTg,5,2,0,0,Doesn't look like much when you pass by but th...,2020-04-23 14:30:52,Kaku Latin Food,...,PA,19134,39.990395,-75.104252,5.0,5,1,"{'RestaurantsDelivery': 'True', 'RestaurantsTa...","Cajun/Creole, Caribbean, Restaurants, Event Pl...","{'Monday': '8:0-19:0', 'Tuesday': '8:0-19:0', ..."
6989917,jH5Z2Z38c32uUogmPLxLVg,AKXL58tPS_jNdT5DH5NhhA,BEuGzy5gxtGyOEk8iwDfTg,5,1,1,0,Need to check out this place if you are in the...,2020-11-23 23:10:04,Kaku Latin Food,...,PA,19134,39.990395,-75.104252,5.0,5,1,"{'RestaurantsDelivery': 'True', 'RestaurantsTa...","Cajun/Creole, Caribbean, Restaurants, Event Pl...","{'Monday': '8:0-19:0', 'Tuesday': '8:0-19:0', ..."

In [20]:
import pandas as pd
import json

# Assuming merged_df is your dataframe
grouped = filtered_df.groupby('business_id')

for business_id, group in grouped:
    # Getting business details - assuming 'name' is a column with business name
    # Add other columns as needed
    business_details = group[['name', 'business_id', 'categories']].iloc[0].to_dict()
    
    # Getting reviews - assuming 'review_text' is the column with the review text
    # Adjust the column name based on your dataframe
    reviews = group['text'].tolist()
    
    # Creating a dictionary with business details and reviews
    data = {
        'business_details': business_details,
        'reviews': reviews
    }
    
    # Creating a unique filename using the business ID
    filename = f'DataCollection/DataAsJsons/business_{business_id}.json'
    
    # Saving the data to a JSON file
    with open(filename, 'w') as f:
        json.dump(data, f, indent=4)